version: '2'

services:
  master:
    image: lowet84/lizardfs-master
    restart: always
    build: build/master
    network_mode: "host"
    ports:
    - 9419:9419
    - 9420:9420
    - 9421:9421

  cgi:
    image: lowet84/lizardfs-cgi
    build: build/cgi
    restart: always
    network_mode: "host"
    ports:
    - 9425:9425
    environment:
    - MFSMASTER=home.test
  
  chunk:
    image: lowet84/lizardfs-chunk
    build: build/chunk
    restart: always
    network_mode: "host"
    environment:
    - MFSMASTER=home.test
    volumes:
    - mfschunk:/mnt
    ports:
    - 9422:9422

volumes:
  mfschunk:
